[trace]
format = 'compact'

[database]
type = 'postgres'
host = 'localhost'
port = 15432
db = 'chat'
user = 'chat'
passwd = 'chat'
allow_list = ['public.test']

[datamap]
integer = ['integer', 'bigint', 'bigserial', 'smallint', 'smallserial', 'serial']
float = ['double precision', 'numeric', 'real']
string = ['character', 'character varying', 'text']
date = ['date', 'time', 'timestamp']
bool = ['boolean']
